export const GET_PRODUCT_CATGORY_LISTING_SUCCESS = "GET_PRODUCT_CATGORY_LISTING_SUCCESS";
export const GET_PRODUCT_CATGORY_LISTING_ERROR = "GET_PRODUCT_CATGORY_LISTING_ERROR";
export const GET_FEATURED_PRODUCT_SUCCESS = "GET_FEATURED_PRODUCT_SUCCESS";
export const GET_FEATURED_PRODUCT_ERROR = "GET_FEATURED_PRODUCT_ERROR";
export const GET_PARENT_CATEGORY_SUCCESS = "GET_PARENT_CATEGORY_SUCCESS";
export const GET_PARENT_CATEGORY_ERROR = "GET_PARENT_CATEGORY_ERROR";
export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
export const GET_LANGUAGE_ERROR = "GET_LANGUAGE_ERROR";